#ifndef _IN_ACCESSIBILITY_ACCESSIBILITY_RELATIONSHIP_H
#define _IN_ACCESSIBILITY_ACCESSIBILITY_RELATIONSHIP_H

#include "types.h"

enum accessibilityrelationship {
	ACCESSIBILITY_RELATIONSHIP_UNKNOWN = 0,
	ACCESSIBILITY_RELATIONSHIP_HOSTILE = 1,
	ACCESSIBILITY_RELATIONSHIP_FRIENDLY = 2,
	ACCESSIBILITY_RELATIONSHIP_NEUTRAL = 3,
	ACCESSIBILITY_RELATIONSHIP_PROTECTED = 4,
};

s32 accessibilityRelationshipClassifyCharacter(struct prop *prop);

#endif
