set(REQUIRED_VARIABLES
  PD_PACKAGE_BINARY
  PD_PACKAGE_RUNTIME_DIRECTORY
  PD_PACKAGE_GCC_RUNTIME_NAME
  PD_PACKAGE_CONTROLLER_NAME
  PD_PACKAGE_CONFIG
  PD_PACKAGE_ROM_INSTRUCTIONS
  PD_PACKAGE_PROJECT_LICENSE
  PD_PACKAGE_TOLK_LICENSE
  PD_PACKAGE_NVDA_LICENSE
  PD_PACKAGE_STAGING
  PD_PACKAGE_ARCHIVE
)

foreach(VARIABLE_NAME IN LISTS REQUIRED_VARIABLES)
  if(NOT DEFINED ${VARIABLE_NAME} OR "${${VARIABLE_NAME}}" STREQUAL "")
    message(FATAL_ERROR "Windows package variable is missing: ${VARIABLE_NAME}")
  endif()
endforeach()

set(PACKAGE_FILES
  "${PD_PACKAGE_BINARY}"
  "${PD_PACKAGE_RUNTIME_DIRECTORY}/libwinpthread-1.dll"
  "${PD_PACKAGE_RUNTIME_DIRECTORY}/${PD_PACKAGE_GCC_RUNTIME_NAME}"
  "${PD_PACKAGE_RUNTIME_DIRECTORY}/SDL2.dll"
  "${PD_PACKAGE_RUNTIME_DIRECTORY}/zlib1.dll"
  "${PD_PACKAGE_RUNTIME_DIRECTORY}/Tolk.dll"
  "${PD_PACKAGE_RUNTIME_DIRECTORY}/${PD_PACKAGE_CONTROLLER_NAME}"
  "${PD_PACKAGE_CONFIG}"
  "${PD_PACKAGE_ROM_INSTRUCTIONS}"
  "${PD_PACKAGE_PROJECT_LICENSE}"
  "${PD_PACKAGE_TOLK_LICENSE}"
  "${PD_PACKAGE_NVDA_LICENSE}"
)

foreach(PACKAGE_FILE IN LISTS PACKAGE_FILES)
  if(NOT EXISTS "${PACKAGE_FILE}")
    message(FATAL_ERROR "Required Windows package input is missing: ${PACKAGE_FILE}")
  endif()
endforeach()

file(REMOVE_RECURSE "${PD_PACKAGE_STAGING}")
file(REMOVE "${PD_PACKAGE_ARCHIVE}")
file(MAKE_DIRECTORY
  "${PD_PACKAGE_STAGING}"
  "${PD_PACKAGE_STAGING}/data"
  "${PD_PACKAGE_STAGING}/licenses/tolk"
)

file(COPY "${PD_PACKAGE_BINARY}" DESTINATION "${PD_PACKAGE_STAGING}")
file(COPY
  "${PD_PACKAGE_RUNTIME_DIRECTORY}/libwinpthread-1.dll"
  "${PD_PACKAGE_RUNTIME_DIRECTORY}/${PD_PACKAGE_GCC_RUNTIME_NAME}"
  "${PD_PACKAGE_RUNTIME_DIRECTORY}/SDL2.dll"
  "${PD_PACKAGE_RUNTIME_DIRECTORY}/zlib1.dll"
  "${PD_PACKAGE_RUNTIME_DIRECTORY}/Tolk.dll"
  "${PD_PACKAGE_RUNTIME_DIRECTORY}/${PD_PACKAGE_CONTROLLER_NAME}"
  DESTINATION "${PD_PACKAGE_STAGING}"
)
file(COPY "${PD_PACKAGE_CONFIG}" DESTINATION "${PD_PACKAGE_STAGING}")
file(COPY "${PD_PACKAGE_PROJECT_LICENSE}" DESTINATION "${PD_PACKAGE_STAGING}")
file(COPY "${PD_PACKAGE_ROM_INSTRUCTIONS}"
  DESTINATION "${PD_PACKAGE_STAGING}/data")
file(COPY "${PD_PACKAGE_TOLK_LICENSE}"
  DESTINATION "${PD_PACKAGE_STAGING}/licenses/tolk")
file(COPY "${PD_PACKAGE_NVDA_LICENSE}"
  DESTINATION "${PD_PACKAGE_STAGING}/licenses/tolk")

get_filename_component(PACKAGE_ARCHIVE_DIRECTORY
  "${PD_PACKAGE_ARCHIVE}" DIRECTORY)
file(MAKE_DIRECTORY "${PACKAGE_ARCHIVE_DIRECTORY}")

execute_process(
  COMMAND "${CMAKE_COMMAND}" -E tar cf "${PD_PACKAGE_ARCHIVE}"
    --format=zip -- .
  WORKING_DIRECTORY "${PD_PACKAGE_STAGING}"
  RESULT_VARIABLE PACKAGE_RESULT
  ERROR_VARIABLE PACKAGE_ERROR
)

if(NOT PACKAGE_RESULT EQUAL 0)
  message(FATAL_ERROR
    "Unable to create Windows package ${PD_PACKAGE_ARCHIVE}: ${PACKAGE_ERROR}")
endif()

file(REMOVE_RECURSE "${PD_PACKAGE_STAGING}")
message(STATUS "Created Windows package: ${PD_PACKAGE_ARCHIVE}")
